#### Numpy

In [18]:
import numpy

In [19]:
numpy.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [20]:
a=numpy.array([1,2,3,4,5,6,7,8,9,0])

In [21]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [22]:
import numpy as np

In [23]:
n=np.array([12,1,3,14,34,45,6,78,98,654])

In [24]:
n

array([ 12,   1,   3,  14,  34,  45,   6,  78,  98, 654])

In [25]:
a.size

10

In [26]:
n.size

10

In [27]:
a.shape

(10,)

In [28]:
n.shape

(10,)

In [29]:
b=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [30]:
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [31]:
b.size

12

In [32]:
b.shape

(4, 3)

In [33]:
np.array([[11,12],[13,14],[15,16],[16,17]])

array([[11, 12],
       [13, 14],
       [15, 16],
       [16, 17]])

In [34]:
z=np.array([[11,12],[13,14],[15,16],[16,17]])

In [35]:
z

array([[11, 12],
       [13, 14],
       [15, 16],
       [16, 17]])

In [36]:
z.size

8

In [37]:
z.shape

(4, 2)

In [38]:
z.ndim

2

In [39]:
z.reshape(2,4)

array([[11, 12, 13, 14],
       [15, 16, 16, 17]])

In [41]:
z.min()

11

In [42]:
z.max()

17

In [43]:
z.itemsize

4

In [44]:
z.dtype

dtype('int32')

In [45]:
#1byte=8bit
#4byte=32bit
#8byte=64bit

In [46]:
b=np.array([[1,2,3],[4,5,6]],dtype=float)

In [47]:
b

array([[1., 2., 3.],
       [4., 5., 6.]])

In [48]:
b.itemsize

8

In [49]:
b.dtype

dtype('float64')

In [50]:
b.ndim

2

In [51]:
b.min()

1.0

In [52]:
b.max()

6.0

In [53]:
b.shape

(2, 3)

In [54]:
b.size

6

In [55]:
b.reshape(3,2)

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [56]:
c=np.array([[1,2,3],[4,5,6]],dtype="float32")

In [57]:
c

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [59]:
c.dtype

dtype('float32')

In [60]:
c.itemsize

4

In [62]:
d=np.array([[1,2,3],[4,5,6]],dtype='float64')

In [63]:
d

array([[1., 2., 3.],
       [4., 5., 6.]])

In [65]:
d.dtype

dtype('float64')

In [66]:
d=np.array([[1,2,3],[4,5,6]],dtype="float64")

In [67]:
d

array([[1., 2., 3.],
       [4., 5., 6.]])

In [68]:
x=np.array([[1,2],[3,4],[5,6],[7,8],[9,10]],dtype=int)

In [69]:
x

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [70]:
x.dtype

dtype('int32')

In [71]:
x.itemsize

4

In [72]:
x=np.array([[1,2],[3,4],[5,6],[7,8],[9,10]],dtype='int')

In [73]:
x

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [74]:
x.dtype

dtype('int32')

In [75]:
x.itemsize

4

In [76]:
x=np.array([[1,2],[3,4],[5,6],[7,8],[9,10]],dtype='int64')

In [77]:
x

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]], dtype=int64)

In [93]:
l=np.array([[1.2,1],[3.2,1.25],[23,89],[.03,78.569]],dtype=float)

In [94]:
l

array([[1.2000e+00, 1.0000e+00],
       [3.2000e+00, 1.2500e+00],
       [2.3000e+01, 8.9000e+01],
       [3.0000e-02, 7.8569e+01]])

In [95]:
l=np.array([[1.2,1],[3.2,1.25],[23,89],[.03,78.569]],dtype=int)

In [96]:
l

array([[ 1,  1],
       [ 3,  1],
       [23, 89],
       [ 0, 78]])

In [97]:
l=np.array([[1,2,3],[4,5,8]],dtype='float32')

In [98]:
l

array([[1., 2., 3.],
       [4., 5., 8.]], dtype=float32)

In [78]:
x.dtype

dtype('int64')

In [79]:
x.itemsize

8

In [80]:
r=np.arange(16)

In [81]:
r

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [83]:
r=np.arange(16).reshape(4,4)

In [84]:
r

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [85]:
r.dtype

dtype('int32')

In [86]:
r=np.arange(16).reshape(2,8)

In [87]:
r

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [91]:
r=np.arange(16).reshape(8,2)

In [92]:
r

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [102]:
a=np.arange(40).reshape(4,10)

In [103]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [104]:
a.size

40

In [105]:
a.shape

(4, 10)

In [106]:
a.itemsize

4

In [107]:
a.dtype

dtype('int32')

In [108]:
a.min()

0

In [109]:
a.max()

39

In [110]:
a.ndim

2

In [111]:
type(a)

numpy.ndarray

In [112]:
v=np.arange(24).reshape(6,4)

In [113]:
v

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [115]:
v.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [116]:
print(v.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [121]:
m=np.array([[7,6],[9,8],[1,2]],dtype="float32")

In [122]:
m

array([[7., 6.],
       [9., 8.],
       [1., 2.]], dtype=float32)

In [124]:
m.ravel()

array([7., 6., 9., 8., 1., 2.], dtype=float32)

In [125]:
print(m.ravel())

[7. 6. 9. 8. 1. 2.]


In [126]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [127]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [134]:
print(np.zeros([1,2]))

[[0. 0.]]


In [135]:
np.arange(0,40,10).reshape(2,2)

array([[ 0, 10],
       [20, 30]])

In [137]:
a=np.array([[1,2],[3,4],[5,6]],dtype=int)

In [138]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [139]:
b=np.array([[1,2],[3,4],[5,6]],dtype=float)

In [140]:
b

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [141]:
c=a+b

In [143]:
c

array([[ 2.,  4.],
       [ 6.,  8.],
       [10., 12.]])

In [144]:
c=a*b
c

array([[ 1.,  4.],
       [ 9., 16.],
       [25., 36.]])

In [145]:
c=a-b
c

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [147]:
c=a//b
c

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [148]:
a**2

array([[ 1,  4],
       [ 9, 16],
       [25, 36]], dtype=int32)

In [149]:
m=np.random.random([2,3])

In [150]:
m

array([[0.500668  , 0.59048774, 0.30873885],
       [0.58611943, 0.64443258, 0.02446617]])

In [185]:
m=np.random.rand(2,3)

In [186]:
m

array([[0.2850891 , 0.40373308, 0.75577796],
       [0.90828058, 0.18781267, 0.47635408]])

In [187]:
np.random.randn(1,2)

array([[-2.25311366, -0.76370705]])

In [188]:
np.random.random([2,3])

array([[0.45217087, 0.03062097, 0.91335888],
       [0.43603776, 0.40341809, 0.07152147]])

In [189]:
np.random.rand(2,3)

array([[0.19031815, 0.22500764, 0.15083282],
       [0.79046437, 0.7152021 , 0.01738142]])

In [190]:
np.random.randn(5,6)

array([[ 1.22611941,  1.31072939, -0.32603394,  1.43911492, -0.38638088,
        -0.89334151],
       [-0.50633753, -0.9735191 ,  2.48602688,  0.99696087, -0.330241  ,
        -0.12366708],
       [-0.87312659, -1.72916382,  1.2484434 , -1.13979719, -0.58249757,
        -0.06071941],
       [ 0.31326839,  0.90442056,  1.9930006 ,  0.93694696,  0.20284096,
         0.91946457],
       [ 1.73034547, -0.72904668, -0.52863425,  0.95120229, -0.67362863,
        -1.58028292]])

In [154]:
a=np.arange(0,15,3).reshape(1,5)

In [155]:
a

array([[ 0,  3,  6,  9, 12]])

In [156]:
np.exp(a)

array([[1.00000000e+00, 2.00855369e+01, 4.03428793e+02, 8.10308393e+03,
        1.62754791e+05]])

In [157]:
np.sqrt(a)

array([[0.        , 1.73205081, 2.44948974, 3.        , 3.46410162]])

In [159]:
a=np.arange(5)

In [160]:
a

array([0, 1, 2, 3, 4])

In [163]:
b=np.arange(5)


In [166]:
c=print(np.add(a,b))

[0 2 4 6 8]


In [167]:
a=np.arange(10)

In [168]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [169]:
a[0]

0

In [170]:
a[-1]

9

In [171]:
a[2:8:2]

array([2, 4, 6])

In [172]:
a[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [173]:
a[::]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [174]:
a[::1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [175]:
a[::3]

array([0, 3, 6, 9])

In [176]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [177]:
a=np.array([1,2,np.nan,np.nan])

In [178]:
a

array([ 1.,  2., nan, nan])

In [179]:
a=np.array([[1,2],[np.nan,12],[13,np.nan],[11,12]])

In [180]:
a

array([[ 1.,  2.],
       [nan, 12.],
       [13., nan],
       [11., 12.]])

In [183]:
np.random.random([4,3])

array([[0.41639073, 0.35461405, 0.31489478],
       [0.61459361, 0.43834908, 0.16567882],
       [0.00602361, 0.53931388, 0.64820187],
       [0.99533282, 0.11695589, 0.69369841]])