# Numpy

In [158]:
import numpy as np
from numpy import random
from numpy.random import random,rand,randn,randint

### One-dimensional array or vector

In [58]:
a=np.array([1,2,3,4,5,6],dtype=int)
a

array([1, 2, 3, 4, 5, 6])

In [180]:
a=np.array([np.nan,2,3,4,5,np.nan],dtype='float64')
a

array([nan,  2.,  3.,  4.,  5., nan])

In [59]:
a=np.array([1,2,3,4,5,6],dtype=float)
a

array([1., 2., 3., 4., 5., 6.])

In [63]:
a=np.array([1,2,3,4,5,6],dtype='float32')
a

array([1., 2., 3., 4., 5., 6.], dtype=float32)

In [194]:
a=np.array([1.2,3.4,6.7,8.9,9.0,2.33],dtype='int64')
a

array([1, 3, 6, 8, 9, 2], dtype=int64)

In [139]:
a.size

6

### INDEXING AND SLICING IN ONE-DIMENSION ARRAY OR VECTOR

In [195]:
#INDEXING
print(a[0])
print(a[-1])
print(a[3])

1
2
8


In [196]:
a[-6]


1

In [156]:
#SLICING
print(a[0:3])
print(a[-3:-1]) #we always tend to right direction.Ergo,we cant take here print(a[-1:-3])
print(a[3:5])

[4 3 6]
[8 9]
[8 9]


In [70]:
a.itemsize

8

In [71]:
a.shape

(6,)

In [72]:
a.ravel()

array([1, 3, 6, 8, 9, 2], dtype=int64)

In [73]:
a.max()

9

In [74]:
a.min()

1

In [75]:
a.argmax()

4

In [76]:
a.argmin()

0

In [78]:
a.dtype

dtype('int64')

In [79]:
a.ndim

1

### two-dimensional array or matrix

In [66]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]],dtype=float)
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [144]:
b=np.array([[1.6,2.3,4.5],[3.4,5.6,7],[9.8,8.0,6]],dtype=int)
b

array([[1, 2, 4],
       [3, 5, 7],
       [9, 8, 6]])

### INDEXING AND SLICING IN ONE-DIMENSION ARRAY OR VECTOR

In [147]:
print(b[0][0])
print(b[2][1])
#or we can write as-
print(b[2,1])

1
8
8


In [149]:
print(b[1:2,0:2])
print(b[2:,1:])
print(b[1:,0:2])

[[3 5]]
[[8 6]]
[[3 5]
 [9 8]]


In [151]:
b[1,1]=6
b

array([[1, 2, 4],
       [3, 6, 6],
       [9, 8, 6]])

In [152]:
b[1,2]=7
b

array([[1, 2, 4],
       [3, 6, 7],
       [9, 8, 6]])

In [80]:
b.size

9

In [81]:
b.itemsize

4

In [82]:
b.shape

(3, 3)

In [83]:
b.ravel()

array([1, 2, 4, 3, 5, 7, 9, 8, 6])

In [84]:
print(b.max())
print(b.argmax())
print(b.min())
print(b.argmin())

9
6
1
0


In [85]:
b.dtype

dtype('int32')

In [86]:
b.ndim

2

### One-dimesional array with the help of ARANGE function

In [88]:
# first elemnt(0) will get included but last element(20) will excluded from the list(start,stop,step)
x=np.arange(0,20,2)
x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [90]:
print(x.size)
print(x.itemsize)
print(x.max())
print(x.argmax())
print(x.min())
print(x.argmin())
print(x.ravel())
print(x.ndim)
print(x.dtype)

10
4
18
9
0
0
[ 0  2  4  6  8 10 12 14 16 18]
1
int32


### two-dimesional array with the help of ARANGE function

In [94]:
x=np.arange(0,20,2).reshape(5,2)
x

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [95]:
print(x.size)
print(x.itemsize)
print(x.max())
print(x.argmax())
print(x.min())
print(x.argmin())
print(x.ravel())
print(x.ndim)
print(x.dtype)

10
4
18
9
0
0
[ 0  2  4  6  8 10 12 14 16 18]
2
int32


### One-dimesional array with the help of LINSPACE function

In [96]:
# first elemnt(0) will get included as well as last element(20) will also get included from the list(start,end,total element)
x=np.linspace(0,20,10)
x

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [97]:
print(x.size)
print(x.itemsize)
print(x.max())
print(x.argmax())
print(x.min())
print(x.argmin())
print(x.ravel())
print(x.ndim)
print(x.dtype)

10
8
20.0
9
0.0
0
[ 0.          2.22222222  4.44444444  6.66666667  8.88888889 11.11111111
 13.33333333 15.55555556 17.77777778 20.        ]
1
float64


### TWO-dimesional array with the help of LINSPACE function

In [100]:
x=np.linspace(0,20,10).reshape(5,2)
x

array([[ 0.        ,  2.22222222],
       [ 4.44444444,  6.66666667],
       [ 8.88888889, 11.11111111],
       [13.33333333, 15.55555556],
       [17.77777778, 20.        ]])

In [101]:
print(x.size)
print(x.itemsize)
print(x.max())
print(x.argmax())
print(x.min())
print(x.argmin())
print(x.ravel())
print(x.ndim)
print(x.dtype)

10
8
20.0
9
0.0
0
[ 0.          2.22222222  4.44444444  6.66666667  8.88888889 11.11111111
 13.33333333 15.55555556 17.77777778 20.        ]
2
float64


### One-dimesional array with the help of RANDOM function

In [109]:
#np.random.random([Rows,Columns]) or; np.random.rand() it takes element b/w 0 to 1.
x=random([4])
x

array([0.32566118, 0.81567468, 0.70946059, 0.57983326])

In [110]:
print(x.size)
print(x.itemsize)
print(x.max())
print(x.argmax())
print(x.min())
print(x.argmin())
print(x.ravel())
print(x.ndim)
print(x.dtype)

4
8
0.8156746824026072
1
0.325661177329998
0
[0.32566118 0.81567468 0.70946059 0.57983326]
1
float64


In [111]:
x=rand(2)
x

array([0.24766746, 0.34676232])

In [ ]:
print(x.size)
print(x.itemsize)
print(x.max())
print(x.argmax())
print(x.min())
print(x.argmin())
print(x.ravel())
print(x.ndim)
print(x.dtype)

In [112]:
#np.random.randn() it takes element b/w postive,negative and zero.it's use for gaussian and normal distribution
x=randn(9)
x

array([-1.27904965, -1.82371168,  0.74562892,  0.1651911 , -1.04908505,
       -1.35267951,  0.07631532,  0.87786298,  1.63508166])

In [197]:
randint(4)
print(x.size)
print(x.itemsize)
print(x.max())
print(x.argmax())
print(x.min())
print(x.argmin())
print(x.ravel())
print(x.ndim)
print(x.dtype)

10
4
6
1
5
0
[5 6 5 6 6 5 6 5 6 5]
2
int32


### Two-dimesional array with the help of RANDOM function

In [114]:
#np.random.random([Rows,Columns]) or; np.random.rand() it takes element b/w 0 to 1.
x=random([4,5])
x

array([[0.52622367, 0.77620134, 0.90002302, 0.05791763, 0.81531362],
       [0.20212935, 0.62093182, 0.84851753, 0.25331426, 0.08604815],
       [0.60019687, 0.77997069, 0.72188914, 0.85468937, 0.29295976],
       [0.36121737, 0.27433423, 0.63116069, 0.43405016, 0.44964522]])

In [115]:
print(x.size)
print(x.itemsize)
print(x.max())
print(x.argmax())
print(x.min())
print(x.argmin())
print(x.ravel())
print(x.ndim)
print(x.dtype)

20
8
0.9000230177335913
2
0.05791763068895883
3
[0.52622367 0.77620134 0.90002302 0.05791763 0.81531362 0.20212935
 0.62093182 0.84851753 0.25331426 0.08604815 0.60019687 0.77997069
 0.72188914 0.85468937 0.29295976 0.36121737 0.27433423 0.63116069
 0.43405016 0.44964522]
2
float64


In [198]:
x=rand(4,5)
x

array([[0.99358326, 0.33310862, 0.70828662, 0.27224218, 0.14758381],
       [0.79556636, 0.17866129, 0.41573003, 0.41067897, 0.5361405 ],
       [0.79608777, 0.61940953, 0.06034931, 0.65078419, 0.39392423],
       [0.84377007, 0.1618599 , 0.54638848, 0.39343229, 0.63799697]])

In [199]:
print(x.size)
print(x.itemsize)
print(x.max())
print(x.argmax())
print(x.min())
print(x.argmin())
print(x.ravel())
print(x.ndim)
print(x.dtype)

20
8
0.9935832594109946
0
0.06034930924012594
12
[0.99358326 0.33310862 0.70828662 0.27224218 0.14758381 0.79556636
 0.17866129 0.41573003 0.41067897 0.5361405  0.79608777 0.61940953
 0.06034931 0.65078419 0.39392423 0.84377007 0.1618599  0.54638848
 0.39343229 0.63799697]
2
float64


In [119]:
#np.random.randn() it takes element b/w postive,negative and zero.it's use for gaussian and normal distribution
x=randn(5,4)
x

array([[ 0.08663132,  0.79446952,  0.84837802, -0.85186484],
       [ 2.14214827, -0.78190628,  2.57773192,  0.75325759],
       [ 0.50953857,  0.1086843 ,  1.67631748,  0.3031945 ],
       [ 0.43544397,  2.54698935,  2.18227601, -0.78346195],
       [ 0.24961262, -0.42211   ,  0.61771926, -0.08805976]])

In [120]:
print(x.size)
print(x.itemsize)
print(x.max())
print(x.argmax())
print(x.min())
print(x.argmin())
print(x.ravel())
print(x.ndim)
print(x.dtype)

20
8
2.5777319162234384
6
-0.8518648390535826
3
[ 0.08663132  0.79446952  0.84837802 -0.85186484  2.14214827 -0.78190628
  2.57773192  0.75325759  0.50953857  0.1086843   1.67631748  0.3031945
  0.43544397  2.54698935  2.18227601 -0.78346195  0.24961262 -0.42211
  0.61771926 -0.08805976]
2
float64


In [201]:
#first element can get included but last element will always get exclude
x=randint(5,7,10).reshape(2,5)
x

array([[6, 6, 5, 6, 6],
       [5, 5, 6, 6, 5]])

### one & two dimensional zero vector

In [130]:
x=np.zeros([])
x

array(0.)

In [131]:
x=np.zeros([4])
x

array([0., 0., 0., 0.])

In [127]:
x=np.zeros([5,5])
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### one & two dimensional unit vector

In [128]:
x=np.ones([])
x

array(1.)

In [129]:
x=np.ones([4])
x

array([1., 1., 1., 1.])

In [132]:
x=np.ones([3,4])
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### creating identity matrix

In [134]:
x=np.eye(2)
x

array([[1., 0.],
       [0., 1.]])

In [135]:
x=np.eye(5)
x

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### NUMPY inbuilt functions 

In [171]:
x=randint(5,7,10).reshape(2,5)
print("\n",x)
print("\n",np.exp(x))
print("\n",np.log(x))
print("\n",np.sqrt(x))
print("\n",np.sin(x))
print("\n",np.cos(x))
print("\n",np.add(x,x))


 [[5 6 5 6 6]
 [5 6 5 6 5]]

 [[148.4131591  403.42879349 148.4131591  403.42879349 403.42879349]
 [148.4131591  403.42879349 148.4131591  403.42879349 148.4131591 ]]

 [[1.60943791 1.79175947 1.60943791 1.79175947 1.79175947]
 [1.60943791 1.79175947 1.60943791 1.79175947 1.60943791]]

 [[2.23606798 2.44948974 2.23606798 2.44948974 2.44948974]
 [2.23606798 2.44948974 2.23606798 2.44948974 2.23606798]]

 [[-0.95892427 -0.2794155  -0.95892427 -0.2794155  -0.2794155 ]
 [-0.95892427 -0.2794155  -0.95892427 -0.2794155  -0.95892427]]

 [[0.28366219 0.96017029 0.28366219 0.96017029 0.96017029]
 [0.28366219 0.96017029 0.28366219 0.96017029 0.28366219]]

 [[10 12 10 12 12]
 [10 12 10 12 10]]


### Broadcasting in Numpy

In [172]:
x

array([[5, 6, 5, 6, 6],
       [5, 6, 5, 6, 5]])

In [173]:
x*3

array([[15, 18, 15, 18, 18],
       [15, 18, 15, 18, 15]])

In [174]:
x+3

array([[8, 9, 8, 9, 9],
       [8, 9, 8, 9, 8]])

In [175]:
x/3

array([[1.66666667, 2.        , 1.66666667, 2.        , 2.        ],
       [1.66666667, 2.        , 1.66666667, 2.        , 1.66666667]])

In [176]:
x-3

array([[2, 3, 2, 3, 3],
       [2, 3, 2, 3, 2]])

In [177]:
x

array([[5, 6, 5, 6, 6],
       [5, 6, 5, 6, 5]])

In [178]:
x**2

array([[25, 36, 25, 36, 36],
       [25, 36, 25, 36, 25]], dtype=int32)

In [179]:
x**3

array([[125, 216, 125, 216, 216],
       [125, 216, 125, 216, 125]], dtype=int32)

In [181]:
x>3

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [182]:
x[x>3]

array([5, 6, 5, 6, 6, 5, 6, 5, 6, 5])

In [183]:
x[x<3]

array([], dtype=int32)

In [187]:
x<6

array([[ True, False,  True, False, False],
       [ True, False,  True, False,  True]])

In [188]:
x[x>3]

array([5, 6, 5, 6, 6, 5, 6, 5, 6, 5])

In [191]:
x[x<6]

array([5, 5, 5, 5, 5])